version: '3.7'

volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/database/data

services:
  redis:
    image: redis:latest
    container_name: cdv-redis

  db:
    image: postgres:11
    container_name: cdv_database
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: userdb
      POSTGRES_DB: carnetdevacunacion
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    security_opt:
      - seccomp:unconfined

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cdv_django
    tty: true
    depends_on:
      - redis
      - db
    volumes:
      - ./:/webapps/carnetdevacunacion
    ports:
      - "7000:7000" # ./manage.py runserver
      - "7001:7001" # ./manage.py shell_plus --notebook
      - "7002:7002" # .debug vscode
    environment:
      - SECRET_KEY="&l313vwhvv+jx=qf1nl^wxti1mohut&)ddnioth$yflcj8hqlc"
    command: >
      bash -c "
      wait-for-it db:5432 --strict --timeout=60 -- django-migrate &&
      poetry lock --no-update &&
      source /opt/venv/bin/activate &&
      ./manage.py runserver 0.0.0.0:7000
      "
