version: "3.7"

services:
  web:
    image: cdv
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cdv
    tty: true
    ports:
      - 80:80
    volumes:
      - ./:/app/vue
      - /app/vue/node_modules
    command: >
      sh -c "
      npm i --package-lock-only &&
      npm run serve -- --port 80"
